# Generated by Django 4.2.4 on 2024-10-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_material_delete_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
    ]
