# Generated by Django 5.0.6 on 2024-09-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_rename_material_types_material_material_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
