# Generated by Django 5.0.6 on 2024-09-27 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0005_rename_name_quiz_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="level",
            new_name="name",
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(default="No option", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_1",
            field=models.CharField(default="No option", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_2",
            field=models.CharField(default="No option", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_3",
            field=models.CharField(default="No option", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_4",
            field=models.CharField(default="No option", max_length=255),
        ),
        migrations.AlterField(
            model_name="userresult",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userresult",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_results",
                to="topics.topic",
            ),
        ),
        migrations.AlterField(
            model_name="userresult",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_answer", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="topics.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
