# Generated by Django 5.0.6 on 2024-10-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0006_rename_level_quiz_name_question_correct_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
